Avnish/carousel
lablueprint/tck-web-app pull request #12
Opened 2022-04-09 05:54 UTC by ascend2001

2022-04-13 23:41 UTC, DiyaBaliga requested changes
Avnish this is brilliant!! Your determination (and problem-solving) skills are astounding, I definitely would've given up on swiper earlier. Your naming improved too, wow such talent.

Before merging with main, just clean up all the remaining comments and in-line styles. There are also some errors with dom nesting that I tried to find solutions to. I think I added comments for most of the changes necessary, but give everything a once over.

The only big issue is with props. Each of the components are expecting the books/collections in different forms and the props are not accurate in a lot of cases. Can you trace through your code and make sure the props are consistent? Keep in mind the form that book objects come from airtable in as well as error-checking at each point. Add notes for what the component is expecting for other developers.

2022-04-13 23:41 UTC, DiyaBaliga commented on src/App.css
> +@font-face {
google fonts have an easier import method, how does your code work? Rather than downloading all the fonts, we can use google imports!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/CollectionPage/CollectionInfo.js
>          <img width="10%" height="10%" align="center" src={picture} alt="author" />
can you change these from in-line styles?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +  /* margin: 20px; */
remove comments with unused code!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +.link{
this doesn't seem to have anything, so you can just delete it!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +.swiper-wrapper{
same here! get rid of comments + unused styles

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
get rid of this disable. if there are any unused vars in the final version, you can definitely get rid of them too!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +// const Airtable = require('airtable');
unused comments

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +    <div className="collectionCard" style={{ background: '#2E3E64' }}>
get rid of in-line styles

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +        <Link class="link" to={`/collection/${Collid}`} style={{ display: 'flex', flexirection: 'row', color: 'white' }}>
move all of these in-line styles to the css file

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
Is this file for Collection Cards? Can you rename it that way?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +/* eslint-disable no-param-reassign */
remove all the eslint-disables and try to resolve the errors!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +      style={{
style :(

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +        className="carousel-button-prev"
className + in-line?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +// refactor the carousel to make these editable:
no longer need these comments

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +/* eslint-disable no-param-reassign */
Can you add a header to this file to explain what the component does and descriptions/format for each parameter?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Navigation/Header.js
> +    <nav className="header" style={{ zIndex: '1' }}>
you can get rid of this! A lot of other people ran into the same issue and added the style to the css.

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.css
comments again

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +    <div className="card" style={{ margin: inCarousel ? '0' : '30px 16px 10px 16px' }}>
in-lines

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/AuthoredWorkCard.js
>  import React from 'react';
Can you get rid of the Authored and Illustrated Work cards? I don't think they are needed anymore

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/BookCarousel.js
> +// refactor the carousel to make these editable:
comments

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/BookCarousel.js
> +/* eslint-disable no-param-reassign */
Get rid of eslint disables + add a header with an explanation for the component for this card too!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/IllustratedWorkCard.js
>  import React from 'react';
get rid of this too!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/OtherWorks.css
>  .related-works-card{
comments

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/OtherWorks.js
> +import RightArrowAuthorPage from '../../Assets/Images/right-arrow-author-page.svg';
can you rename the image files + imports to "right-arrow-grey" and "right-arrow-orange" so that it's more descriptive of the differences? it's kind of confusing as is

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Pages/Home.js
> +      <CollectionDisplay style={{ display: 'flex', justifyContent: 'center' }} />
in-line

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/creatorPage/BookCarousel.js
> +    id: propTypes.number,
ids are strings!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +    id: propTypes.number,
ids are strings!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +  inCarousel: PropTypes.bool.isRequired,
instead of being required, it'd be better to add false as the default!

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +                Collid={element.id}
add a key for each of these elements! (just set it to the id)

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
Actually, these are the smaller collection cards, so can you name them as such?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
>        <body className="CollectionBody">
change this to a div! a body tag can't be a child of a div

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
>    useEffect(getAuthor, []);
This throws errors if the author id is invalid, can you add a check for if the id is MISSING AUTHOR here or handle the case in the component above?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
>            <Link class="link" to={`/creator/${author}`}>
can you also reorganize this so the link to the author isn't nested in the link to the book?

2022-04-13 23:41 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
>            <Link class="link" to={`/creator/${author}`}>
may require some restyling

2022-04-13 23:53 UTC, ascend2001 commented on src/App.css
> +@font-face {
I remember when I was researching the best way to use fonts, downloading them does make the software heavier but it guarantees that the fonts will be rendered in most edge cases for like different devices and stuff. I am obviously down for whatever is preferred tho

2022-04-18 22:16 UTC, DiyaBaliga requested changes
It looks so much better! There are still a lot of remaining console logs and unused commented code that could be cleaned out. I think there are still some comments that I left last time that you haven't resolved, so if you could go through all of your code once to clean it up and address the remaining comments that would be great! There are also still prop type issues. Go through once more and make sure to check ALL of the prop type errors to see where there are issues! I left some comments on how to make this easier, so check that out too!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
>  .collectionCard{
Can you make all css styles lowercase w/ dashes in between rather than camelCase

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +    <div className="collectionCard" style={{ background: '#2E3E64' }}>
I don't think you made this change yet!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +    <div className="card" style={{ margin: inCarousel ? '0' : '30px 16px 10px 16px', display: 'flex', flexDirection: 'column' }}>
in-line style! the ones that aren't conditional should be classes. It could be better if you put everything into css classes and then move the conditional to the className!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +        <Typography className={classes.author} color="text.secondary" style={{ fontFamily: 'DM Sans' }}>
in-line style can be moved to the class!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +BookCard.defaultProps = {
I think you need to add a default for the image as well because it isn't required!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
>                  image={element.fields.image !== undefined ? element.fields.image[0].url : 'MISSING IMAGE'}
There are a ton of inconsistent methods data is passed b/w components like this. Can you change all of the similar 'MISSING IMAGE' or 'MISSING AUTHOR' stuff to just pass an undefined so that the collection/book cards only need to handle that case? That way you don't need all the extra checks

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
>        <Link class="link" to={`/book/${id}`}>
is the class here necessary? I think it's the one throwing the error. Can you check if the link still works without the specification?

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +    id: propTypes.number,
this will throw an error unless you change the id proptype to string!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +        onSlideChange={() => console.log('slide change')}
remove console log

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/creatorPage/BookCarousel.js
> +          onSlideChange={() => console.log('slide change')}
remove console log!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/creatorPage/OtherWorks.js
> +  // const swiperHook = useSwiper();
delete unused comments!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +// import AuthoredWorkCard from './AuthoredWorkCard';
unused comments!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +  // const swiperHook = useSwiper();
unused comments!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +          // loop
unused comments!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +          // className="carousel-button-prev"
unused comments!

2022-04-18 22:16 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +          <div style={{ paddingTop: '20', paddingBottom: '20' }}>
The error is still popping up, I think you need to give the parent divs the key! move the key={element.id} up to this div instead

2022-04-25 07:48 UTC, closed without merging