Avnish/electric boogaloo
lablueprint/tck-web-app pull request #16
Opened 2022-04-14 18:25 UTC by ascend2001

2022-04-14 18:26 UTC, ascend2001 commented
Pretty sure this is branched off of Avnish/Carousel which is understandable since I need carousel components

2022-04-24 09:23 UTC, DiyaBaliga requested changes
Avnish this is brilliant! Thank you so much for debugging everything, it looks great and runs beautifully. There are just a few changes to make to polish everything (removing all ESLint disables, making CSS style naming consistent, renaming files). There were some comments I left that I don't think you noticed the first time. You're debugging was so meticulous, I hate to force you to do more tedious work, but it's really so close and fantastic so far.

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/CollectionPage/BooksInCollectionI.js
> +    setBooks([]);
is this necessary? does it cause any async issues?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +#collectionCard{
it's better to use lowercase w/ dashes instead of camelCase for css styles

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +  /* background: #fff; */
unused comments

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
take out the disable!

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +// const Airtable = require('airtable');
unused comments

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +      style={{
in-line styles!

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
can you rename the file to CollectionCard if it displays only a single collection?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +      {/* <p className="cardText">{description}</p> */}
unused comment

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionDisplay.js
>  import React, { useState, useEffect } from 'react';
What is this component supposed to do? If it only displays the carousel, then you can just import the carousel where needed and delete this file

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +/* eslint-disable prefer-destructuring */
comments

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.css
> +#collectionCard{
^ bump

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
^

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/Collection.js
> +/* eslint-disable no-unused-vars */
^

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +/* eslint-disable prefer-destructuring */
^

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionsCarousel.js
> +// let init = 1;
unused comment

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/creatorPage/BookCarousel.js
> +/* eslint-disable no-param-reassign */
disables

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/CollectionPage/BooksInCollectionI.js
>  import React, { useEffect, useState } from 'react';
Why is this file named BooksInCollectionI instead of BooksInCollection, was that a typo?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/CollectionPage/BooksInCollectionI.js
>            // Speical Prop
```suggestion
          // Special Prop
```

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionDisplay.js
>  import React, { useState, useEffect } from 'react';
bump

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/Collections/CollectionDisplay.js
>  import React, { useState, useEffect } from 'react';
Also can you rename the Collections folder to CollectionsComponents?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/bookHub/BookCard.js
> +      if (name === 'MISSING AUTHOR' || name === 'Anonymous') { setAuthor('Anonymous'); return; }
Rather than use Missing Author and Anonymous can you consolidate the error messages used?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/creatorPage/IllustratedWorkCard.js
Why do the authored and illustrated work cards exist? Can you consolidate them or replace with the book card entirely?

2022-04-24 09:23 UTC, DiyaBaliga commented on src/Components/creatorPage/AuthorInfo.js
Can you rename this file (and the author.css file) to use creator instead of author?

2022-04-25 08:00 UTC, DiyaBaliga approved these changes
There are still a couple comments that you haven't resolved (make sure to show all of the hidden conversations!) but it looks good, thank you for reviewing everything so quickly! Can you make the last few edits, pull from main and resolve the conflicts, and then merge everything?

2022-04-25 09:23 UTC, merged