Avnish/collection page restyle
lablueprint/tck-web-app pull request #18
Opened 2022-04-28 20:04 UTC by ascend2001

Restyled the Collection Page to be more attuned to Figma, added colors and currently viewing to the collection cards.

2022-05-02 06:13 UTC, DiyaBaliga requested changes
It looks beautiful!! I added comments about code cleanup, but this is a huge step up! There are a couple bugs I noticed though.

First, when the page first loads none of the info about the first collection shows! It the header also does not loop until you move off this first slide. Is the active slide not defined on the first load?

There is also some weirdness around the routing. The collection cards add their id to the route when they are clicked, even if it is not the active slide. Changing the active slide using the arrows rather than clicking on a slide does not update the route. Honestly the routing is not necessary at all, so you could get rid of the link updates in the collection card and change the 'collection' route to not be dynamic at all. It is not necessary, but all references to the routes should be cleaned up to not be confusing.

And here are some notes on the styling! We should discuss the later ones with the designers
1. The buttons should have a bigger gap from the slides!
2. I think there might be a bit too much padding around the page
3. The Figma rounds off the edges of the cut of slides. I think the sharp edges help with the illusion that they are sliding off the page/cutting off, but we should ask the designers which they prefer! This also might not be feasible, so consider it yourself first.
4. If you click on one of the adjacent slides rather than an arrow, should the header shift?
5. Responsiveness! Should we just show the center slide if the window is small enough? It also seems like there is too much unused blank space when we get small.

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionPage/CollectionInfo.js
> +      <div className="collection-heading" style={{ fontFamily: 'Work Sans', fontWeight: 'bold' }}>
in-lines!

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/Collection.css
> +    /* overflow: hidden;
unused comments

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionCard.js
> +  Collid, image, name, imageHeightPercent,
change Collid to be camel case collectionId so it is consistent w the others!

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionCard.js
>                style={{
in-lines

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionCard.js
>                style={{
the conditional ones should be the only ones in-line

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionCard.js
> +            {isSlideActive
Great implementation! I do feel like it's a bit weird to have the currently viewing text at all, that the slide is in the center seems to indicate that you are viewing it. But idk we can check with the designers!

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionCard.js
>              style={{
in-line

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionsCarousel.js
> +export const collectionCardColors = ['#393EBA', '#333333', '#F99E16', '#3477DE', '#E85757', '#20B28F'];
eventually this will need to be an array of arrays or a map because there will be specific sets of background and icon colors that need to be with each other!

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Components/CollectionsComponents/CollectionsCarousel.js
> +            element.id === activeSlideId
the only prop that changes when element id is the activeSlide is 'isSlideActive'! Instead of having this long conditional, you can simplify it to just add 'isSlideActive={element.id===activeSlideId}' and get rid of all the excess

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Pages/CollectionPage.js
>    useEffect(getPosts, [collecID]);
why is the function called getPosts? Can you rename it to describe the actual functionality?

2022-05-02 06:13 UTC, DiyaBaliga commented on src/Pages/CollectionPage.js
> +    <div style={{ margin: '4rem 7rem 0rem 7rem' }}>
in-line

2022-05-03 09:06 UTC, ascend2001 commented on src/Components/CollectionsComponents/CollectionsCarousel.js
> +            element.id === activeSlideId
the background color prop also changes

2022-05-05 00:42 UTC, DiyaBaliga reviewed
Looks great bestie! The collection header bug that I mentioned still causes issues on my end, but I'll trust that your header branch fixes that issue. Merge this into that branch and then submit a PR for all the changes together when you can!

2022-05-05 06:32 UTC, closed without merging